# Generated by Django 4.2.4 on 2023-08-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name_plural': 'ТЕМАТИКИ СТАТЬИ'},
        ),
    ]
