# Generated by Django 4.2.4 on 2023-08-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'РАЗДЕЛ'},
        ),
    ]
